version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3001:3001"
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
